### PR TITLE
Fix CI tests fails

### PR DESCRIPTION
**Pull request by Samweli**
When running unit tests for the remote executed scripts the job requests uses the script id instead of the script name. 
These changes updates the used test data to have script id as the script key when fetching script data.

### CODE REVIEW

**Comment by azvoleff** [comment]
The script IDs change when the scripts do (as the IDs are used to ensure the proper script version is run on the API). So to keep the tests up to date in testing the latest version of the scripts we'll need to add a few lines to the `update_script_ids` function within [tasks.py](https://github.com/ConservationInternational/trends.earth/blob/main/tasks.py#L513), to ensure that function also updates the script IDs used in the tests.

@Samweli can you add that update? Once done this one should be good to merge

**Comment by Samweli** [comment]
> The script IDs change when the scripts do (as the IDs are used to ensure the proper script version is run on the API). So to keep the tests up to date in testing the latest version of the scripts we'll need to add a few lines to the `update_script_ids` function within [tasks.py](https://github.com/ConservationInternational/trends.earth/blob/main/tasks.py#L513), to ensure that function also updates the script IDs used in the tests.
> 
> @Samweli can you add that update? Once done this one should be good to merge

sure @azvoleff, thanks.

**Comment by azvoleff** [comment]
Good point - makes sense. I'll merge

**Comment by amyburness** [comment]
#821

**Pull request merged**
