### PR TITLE
Dataset delete. Fixes #403

### LINKED ISSUE #403: Allow deleting a dataset
Each item in the datasets list shall show a `delete` button and pressing it shall ultimately result in the dataset being deleted from the local filesystem. This action needs to be guarded by an additional confirmation dialog, where the user must confirm the intention of having the dataset be deleted.

The action of deleting a dataset must result in the deletion of:

- The actual dataset
- The json sidecar file that we are using to store the dataset details

### NOTE

The `delete` button should only be enabled for datasets that are available locally.

### PR DESCRIPTION
**Pull request by luipir**

### CODE REVIEW

**Comment by ricardogsilva** [comment]
I'll wait for #412 before I review this

**Comment by ricardogsilva** [comment]
@luipir 

can you please rebase this now that #412 has been merged? I'll proceed to review then

**Comment by luipir** [comment]
doing now

**Comment by luipir** [comment]
@ricardogsilva @Samweli rebased... please review when you can

**Review by ricardogsilva — CHANGES_REQUESTED** [review]
Seems to work OK.

The only thing missing, as mentioned in the original issue description, is that we need to use a confirmation dialog where the user confirms the action to delete a dataset before deleting.

Please add that and then I'll be +1 for merging

**Comment by luipir** [comment]
> is that we need to use a confirmation dialog

gosh! I completly forgot it! thanks to check it out!

**Comment by luipir** [comment]
rebased again after merge of PR about sorting dataset

**Review by ricardogsilva — APPROVED** [review]
Looks good to me, thanks!

**Comment by ricardogsilva** [comment]
@Samweli, I'm happy with the functionality. I leave the merging of this up to you now

**Review by Samweli — APPROVED** [review]

**Pull request merged**
