### PR TITLE
Update on area name value when opening settings for first time.

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/ConservationInternational/trends.earth/issues/378

### CODE REVIEW

**Comment by luipir** [comment]
wait for @ricardogsilva comments about this aspects

**Review by luipir — APPROVED** [review]

**Comment by ricardogsilva** [comment]
@luipir  @Samweli 

Is this good to merge? Sorry if I missed something, but do you need me to comment on this?

**Comment by Samweli** [comment]
> Is this good to merge?

yes it is @ricardogsilva

**Comment by ricardogsilva** [comment]
@luipir
If this is ready to merge, please go ahead and merge it. No need to wait for me since I've not been involved as a reviewer

**Comment by luipir** [comment]
> @luipir
> If this is ready to merge, please go ahead and merge it. No need to wait for me since I've not been involved as a reviewer

ok...

**Pull request merged**
