### PR TITLE
Add load base map button in datasets tab

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/ConservationInternational/trends.earth/issues/404
Screenshot
load_base_map

### CODE REVIEW

**Review by luipir — CHANGES_REQUESTED** [review]
you should remove LDMP/shcemas from the PR, for the rest LGTM

**Review by ricardogsilva — CHANGES_REQUESTED** [review]
Looks good, but please remove that `schemas` file from the PR. After that, LGTM!

**Review by luipir — APPROVED** [review]

**Comment by luipir** [comment]
I'll open a low priority issue @Samweli. can you add the button icon to load base map? the same icon as in Visualization Tool menu action. Just to remain uniform

**Comment by Samweli** [comment]
> I'll open a low priority issue @Samweli. can you add the button icon to load base map? the same icon as in Visualization Tool menu action. Just to remain uniform

right @luipir!

**Pull request merged**
