### PR TITLE
fix Nonetype value passing error

### PR DESCRIPTION
**Pull request by Samweli**
This PR fixes an error that I kept getting which is related to progress update on an already downloaded Dataset. 
see
image

### CODE REVIEW

**Comment by luipir** [comment]
@Samweli I suppose you had this issue because you have some local processed data. Isn't it? 

BTW better a fix that do some decision about values to show instead than do nothing.
In case of local processing we do not have status, progres nor source => all this data will be managed by the Datasets class when loading a JSON from local process.

If it is not a JOSN from local process => please give me info how did you generate it.

I would close this PR in favour of a more general management.

**Comment by Samweli** [comment]
> @Samweli I suppose you had this issue because you have some local processed data. Isn't it?
> 
> BTW better a fix that do some decision about values to show instead than do nothing.

@luipir yes, I will be happy if we come with fix for it sooner :smile: , as the error keeps showing up to me while testing functionalities, and some times QGIS crashes!

**Comment by luipir** [comment]
> error keeps showing up

I need to know in what case and with what JSOn you are facing this error.
BTW crash shouldn't be related with this issue

**Comment by Samweli** [comment]
@luipir using the latest changes the error does not occur at all, I ll try to reproduce it, if not successful will close this.

**Comment by Samweli** [comment]
@luipir @ricardogsilva closing this, the error doesn't occur anymore when using `decision-trees` branch latest changes,

**Pull request closed without merging**
