### PR TITLE
Advanced parameters refactoring in the Settings dialogue. Fixes #359

### LINKED ISSUE #359: Implement Advanced parameters in the Settings dialogue
According with the implementation plan, the Settings section shall be redesigned to look like the below mock-up

settings-dialogue

Implement the *advanced* section so that both the GUI and the underlying code reflect the above vision.

### Notes

- Take heed of the notes shown on the mock-up, to the right of the dialogue.
- If needed, review the initial proposal document (which is not being shared publicly for now)
- Store these settings in `QgsSettings`. Use `trends_earth` as the base setting key
- The `base data directory` setting shall be used by all algorithms as the root for data storage. Make sure this is also implemented in each algorithm's code. We want this plugin to keep working as we introduce the changes

### PR DESCRIPTION
**Pull request by luipir**
fixes #359

### CODE REVIEW

**Comment by luipir** [comment]
@ricardogsilva I'm going to rebase and merge thsi PR

**Comment by luipir** [comment]
rebased and squashed in a single commit

**Comment by luipir** [comment]
@ricardogsilva do the last check (I did) and merge it... or betetr to manage this step to @Samweli becouase he has to rebase his PR based on this?

**Review by ricardogsilva — APPROVED** [review]
Thanks for your work!

I noticed a couple minor things which I fixed in a commit in order for us to avoid another review cycle for this. These were:

- The signal for showing the password reset dialogue was being configured twice, which caused the dialogue to stay open
- There was no default for the base directory. I set it to a `trends_earth_data` directory under the user's home dir

**Pull request merged**
