### PR TITLE
 Algorithm dialog updates

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/ConservationInternational/trends.earth/issues/437

Adds changes to all algorithms execution dialogs as proposed in the issue above.

Screenshot showing updates on some algorithms dialogs UI

algorithms_update_v2

### CODE REVIEW

**Comment by ricardogsilva** [comment]
@Samweli 

Please fix the conflicts and let me know whether this is ready to be reviewed

**Comment by Samweli** [comment]
> @Samweli 
> 
> Please fix the conflicts and let me know whether this is ready to be reviewed

sure @ricardogsilva working on this.

**Comment by Samweli** [comment]
@ricardogsilva I have update this PR with the latest changes.

**Review by ricardogsilva — CHANGES_REQUESTED** [review]
Nice work, it looks great!

Only thing I would like to be different is to have a single collapsible area for everything that is considered _advanced_

**Comment by Samweli** [comment]
> Only thing I would like to be different is to have a single collapsible area for everything that is considered _advanced_

@ricardogsilva this is not a good UI choice, as we will end up with ungrouped components all in one collapsible group or grouped components nested inside one collapsible group.

**Pull request merged**
