### PR TITLE
Hook local data import button

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/ConservationInternational/trends.earth/issues/406

### CODE REVIEW

**Review by luipir — CHANGES_REQUESTED** [review]
please remove from the PR (.e.g do not use git commit --all  ;) )
schemas.py
setup.py

**Comment by luipir** [comment]
other this fix of the PR, LGTM

**Comment by Samweli** [comment]
> please remove from the PR (.e.g do not use git commit --all ;) )
> schemas.py
> setup.py

@luipir thanks, done.

**Review by luipir — APPROVED** [review]

**Comment by Samweli** [comment]
thanks @luipir

**Pull request merged**
